spring:
  cloud:
    gateway:
      routes:
        - id: admin_route
          uri: lb://v2shop-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /v2shop-admin/$\{segment}